name: CD

on:
  release:
    types:
    - created

jobs:
  linux_windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

    - name: Install rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

    - name: Build the executable
      run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

    - name: Tar binaries
      run: |
        tar -czvf textpod-gnu-linux-x86_64.tar.gz target/x86_64-unknown-linux-musl/release/textpod
        zip -j textpod-windows.zip target/x86_64-pc-windows-gnu/release/textpod.exe

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["textpod-gnu-linux-x86_64.tar.gz", "textpod-windows.zip"]'

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install rustup targets
      run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

    - name: Build the executable
      run: cargo build --release --target=x86_64-apple-darwin --target=aarch64-apple-darwin

    - name: Zip binaries
      run: 
        zip -j textpod-macos-x86_64.zip target/x86_64-apple-darwin/release/textpod
        zip -j textpod-macos-aarch64.zip target/aarch64-apple-darwin/release/textpod

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["textpod-macos-x86_64.zip", "textpod-macos-aarch64.zip"]'
